### ISSUE TITLE
Bagous ending condition?

### ISSUE THREAD

**Issue by StickieBE** [LifeAdmin-cmd/Password-Defender#56]
When playing on server player bavouzet with bike into wall of map and then database corrupt why? I only have selection male and female.
all cookies bavouzett and I player end in bagous ending

**Comment by ArmaWizard** [comment]
Hello! The game also has pinguin and I can not understand how to clean up the selection of men and women, I had only male.

**Comment by LifeAdmin-cmd** [comment]
No worries, we will remove Tractor from the game for being too buggy rn

**Comment by Floyo66** [comment]
ahh yes i completely understand this conversation
